name: CI

on:
  - push
  - pull_request

env:
  DEFAULT_PYTHON_VERSION: 3

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Use Python ${{ env.DEFAULT_PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.DEFAULT_PYTHON_VERSION }}
          cache: pip
      - name: Install project dependencies
        run: python -m pip install -r requirements.txt
      - name: Install pylint
        run: python -m pip install pylint
      - name: Run linter
        run: python -m pylint --output-format colorized --max-line-length 88 ./fileproxy
  test:
    name: Test
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - ubuntu-24.04-arm
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build application image
        run: docker build --tag fileproxy:dev .
      - name: Create application container
        run: |
          docker create --network host --name fileproxy fileproxy:dev
      - name: Start application container
        run: docker start fileproxy
      - name: Wait for application to be available
        run: curl -I --retry 20 --retry-all-errors --retry-delay 1 http://localhost:8000/
      - name: Test document conversion for HTML
        run: |
          curl -I -H "accept: text/html" http://localhost:8000/
      - name: Test document conversion for Turtle
        run: |
          curl -I -H "accept: text/turtle" http://localhost:8000/
      - name: Test document conversion for N3
        run: |
          curl -I -H "accept: text/n3" http://localhost:8000/
      - name: Test document conversion for N-Triples
        run: |
          curl -I -H "accept: application/n-triples" http://localhost:8000/
      - name: Test document conversion for JSON-LD
        run: |
          curl -I -H "accept: application/ld+json" http://localhost:8000/
      - name: Test document conversion for RDF+XML
        run: |
          curl -I -H "accept: application/rdf+xml" http://localhost:8000/
      - name: Test document conversion for HTML with type-specific template
        run: |
          curl -I -H "accept: text/html" http://localhost:8000/webid
      - name: Test document conversion for HTML with Markdown
        run: |
          curl -I -H "accept: text/html" http://localhost:8000/blog/post
      - name: Test HTTP redirection for owl:sameAs
        run: |
          curl -I http://localhost:8000/redirected
      - name: Stop application container
        if: always()
        run: docker stop fileproxy
  docker:
    name: Docker
    needs: test
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - ubuntu-24.04-arm
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: fileproxy:dev
